### ISSUE TITLE
bower i

### ISSUE THREAD

**Issue by larryhengl** [foxdonut/adventures-reactive-web-dev#1]
Hi @foxdonut , thanks for sharing all of this work.  I am just now playing with the client-elm in my efforts to learn Elm.

I noticed that your step for running bower (for the bootstrap lib) says to run it in each client-*, but that didn't work as it was looking for the bower.json file, which lives at the top.  
...in the readme where it says:
```
# from the top-level directory
cd client-<example> # replace with directory of the example you want to run
npm i
bower i
```
...shouldn't `cd client-*` then run `bower i`.  Should stay at top and run it, which works fine.

thx!

**Comment by foxdonut** [comment]
You are absolutely right, thank you for spotting that @larryhengl .
